name: Build + Publish to Github Pages

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: rustup target add wasm32-unknown-unknown
    - run: cargo install wasm-bindgen-cli
    - name: Use Node.js 24.x
      uses: actions/setup-node@v4
      with:
        node-version: 24.x
        cache: 'npm'
    - run: npm ci
    - name: Generate TypeScript bindings
      run: cargo run
      working-directory: './lib/livesplit-core/capi/bind_gen'
    - name: Compile livesplit-core
      run: cargo rustc -p livesplit-core-capi --crate-type cdylib --features wasm-web --target wasm32-unknown-unknown
      working-directory: './lib/livesplit-core'
      env:
        RUSTFLAGS: '-C target-feature=+bulk-memory,+mutable-globals,+nontrapping-fptoint,+sign-ext,+simd128,+extended-const,+multivalue,+reference-types,+tail-call'
    - name: Generate wasm bindings
      run: wasm-bindgen --encode-into always --target web --reference-types ./lib/livesplit-core/target/wasm32-unknown-unknown/debug/livesplit_core.wasm --out-dir ./src/livesplit-core
    - name: Copy TypeScript bindings into source directory
      run: cp ./lib/livesplit-core/capi/bindings/wasm_bindgen/web/{index,preload}.ts ./src/livesplit-core
    - run: npm run build
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v4
      with:
        path: './dist/pb-pasta/browser'

  deploy:
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      pages: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
